# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\Miniconda3-x64"

  matrix:
      - PYTHON_VERSION: "2.7"
      - PYTHON_VERSION: "3.4"
      - PYTHON_VERSION: "3.5"
      - PYTHON_VERSION: "3.6"

platform:
    -x64

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "SET MPLBACKEND=agg"

    # Install the build and runtime dependencies of the project.
    # Create a conda environment
    - "conda update -q --yes conda"
    - "conda create -q --yes -n test python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of numpy and dependencies
    - "conda install --yes -c conda-forge numpy nose setuptools Cython
    matplotlib msinttypes"
    - "pip install -e ."

# Not a .NET project
build: false

test_script:
  - "nosetests --nologcapture -sv cykdtree"

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
